#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'optparse'
require './lib/pull_request_stats.rb'

option = {}
OptionParser.new do |opt|
  opt.on('-t VALUE') { |v| option[:token] = v }
  opt.on('-r VALUE') { |v| option[:repo] = v }
  opt.parse!(ARGV)
end

puts PullRequestStats.call(option[:token], option[:repo])
